---
#- name: Role ensures that the socks tunnel is setup
#  hosts: localhost
#  connection: local
#  gather_facts: false
#  roles:
#    - ansible-role-socks5-tunnel-nopassphrase
# 
- hosts: all
  gather_facts: no
  tasks:
    - name: Synchronization using rsync protocol (push)
      synchronize:
        src: roles/
        dest: /tmp/roles/
        #use_ssh_args: yes
        rsync_opts:
           - --rsh='ssh -q -oProxyCommand="ssh -q -i $JH2_SSH_PRIVATE_KEY -W %h:%p -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oProxyCommand=""ssh -q -i  $JH1_SSH_PRIVATE_KEY -W {{ jh2_ip }}:{{ jh2_ssh_port }} -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null {{ jh1_ssh_user }}@{{ jh1_ip }}"" {{ jh2_ssh_user }}@{{ jh2_ip }}"'

    - shell: echo Hello `hostname`; ls /tmp/roles
      register: result
