---
- name: Create temporary file to collect applicable inventory_hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create temporary file
      tempfile:
        state: file
        suffix: temp
      register: tempfile
    - set_fact:
        tempfile: "{{ tempfile.path }}"

- name: Collect applicable inventory_hosts with delegate_to method 1
  hosts: all
  gather_facts: false
  tasks:
    - set_fact:
        all_inventory_hosts: "{{ ansible_play_hosts_all }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true

- name: Collect applicable inventory_hosts with delegate_to method 2
  hosts: all
  gather_facts: false
  serial: 1
  tasks:
    - lineinfile: dest="{{ hostvars['127.0.0.1']['tempfile'] }}" line="{{ inventory_hostname }}" state=present create=yes
      delegate_to: localhost

- name: Delete temporary file after setting inventory_hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: "{{ all_inventory_hosts }}"
    - name: Get the inventory_hosts
      shell: |
        cat {{ tempfile }}
      register: inventory_hosts_output
    - name: Register the inventory_hosts
      set_fact:
        inventory_hosts: "{{ inventory_hosts_output.stdout_lines }}"
    - name: use the registered var and the file module to remove the temporary file
      file:
        path: "{{ tempfile }}"
        state: absent
      when: tempfile is defined

