---
- name: Use the synchronize module across multiple jumphosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Synchronization using rsync protocol (push)
      synchronize:
        src: roles/
        dest: /tmp/roles/
        use_ssh_args: yes
        dest_port: "{{ ansible_port }}"
        delete: yes
    - name: Show hello `hostname` using the new ansible_ssh_common_args
      shell: |
        echo Hello `hostname`
