---
- name: Role ensures that the ssh keys are added
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ansible-role-ssh-add-jumphosts-all

- name: Use the synchronize module across multiple jumphosts
  hosts: all
  gather_facts: no
  tasks:
    - block:
        - name: Synchronization using rsync protocol (push)
          synchronize:
            src: roles/
            dest: /tmp/roles/
            use_ssh_args: yes
            dest_port: "{{ ansible_port }}"
            delete: yes
      vars:
        ansible_ssh_common_args: -A ssh -o Port={{ jh1_ssh_port }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -A {{ jh1_ip }} ssh -o Port={{ jh2_ssh_port }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -A {{ jh2_ip }} ssh -o Port={{ jh3_ssh_port }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -A {{ jh3_ip }} ssh -o Port={{ jh4_ssh_port }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -A {{ jh4_ip }} ssh -o Port={{ jh5_ssh_port }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -A {{ jh5_ip }}
 
