---
- hosts: all
  gather_facts: false
  serial: 1
  tasks:
    #- set_fact:
    #    host_list: "{{ groups['all'] }}"
    #  run_once: true
    #  delegate_to: localhost
    - lineinfile: dest=/tmp/alexeihosts line="{{ inventory_hostname }}" state=present create=yes
      delegate_to: localhost
    - set_fact:
        hostnames: "{{ (hostvars['127.0.0.1']['hostnames']|default([])) + [inventory_hostname] }}"
      delegate_to: localhost
      delegate_facts: true

- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg:  "{{ groups['all'] }}"
    - debug:
        msg:  "{{ hostnames }}"
    - shell: |
        cat /tmp/alexeihosts
