---
- name: Role ensures that the socks tunnel is setup for connection to vault. This does not use ssh-agent.
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ansible-role-socks5-tunnel

- name: Collect applicable inventory_hosts with delegate_to method 1
  hosts: all
  gather_facts: false
  tasks:
    - set_fact:
        target_hosts: "{{ ansible_play_hosts_all }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true

- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    api_key: ""
    app_id: BotApp
    auth_secret_path: "/authn/myConjurAccount/admin/authenticate"
    vault_secret_path: "/secrets/myConjurAccount/variable/{{ app_id }}%2F"
    vault_url: "https://aakrhel001.yellowykt.com:8443"
    proxy: "{{ jh1_socks_port if jh1_socks_port is defined else jh_socks_port }}"
    #target_hosts: ["aakrhel001","aakrhel002","testaws-001","testaws-002","testaws-003"]
  tasks:
    - name: Retrieve the token
      uri:
        url: "{{ vault_url }}{{ auth_secret_path }}"
        method: POST
        body: "{{ api_key }}"
        return_content: yes
        socks5_proxy: "{{ proxy }}"
      register: result
    - debug:
        msg: "{{ result }}"




