---
- hosts: all
  gather_facts: false
  tasks:
    - set_fact:
        host_list: "{{ groups['all'] }}"
      run_once: true
      delegate_to: localhost

- hosts: all
  gather_facts: no
  tasks:
    - debug:
        msg:  "{{host_list}}"
    - set_fact:
        hostnames: "{{ [] }}"
    - set_fact:
        hostnames: "{{ hostnames + [inventory_hostname] }}"
      delegate_to: localhost
