---
- name: Role ensures that the socks tunnel is setup
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ansible-role-socks5-tunnel

- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    token: myroot
    vault_secret_path: /testkv/data/testsecrets/jumphost/
    #vault_url: http://ec2-52-201-237-93.compute-1.amazonaws.com:1234
    #proxies: '{}'
    #vault_url: http://172.17.0.3:1234
    #proxies: '{"http":"socks5h://localhost:1234","https":"socks5h://localhost:1234"}'
    vault_url: http://aakrhel001.yellowykt.com:1234
    proxies: '{"http":"{{ jh1_socks_port if jh1_socks_port is defined else jh_socks_port }}","https":"{{ jh1_socks_port if jh1_socks_port is defined else jh_socks_port }}"}'
  tasks:
    - debug:
        msg:
          - "vault_url: {{ vault_url }}"
          - "proxies: {{ proxies }}"
          - "vault_secret_path: {{ vault_secret_path }}"
    - debug:
        msg:
          - my_ssh_user: "{{ lookup('hashi_vault2', 'secret={{ vault_secret_path }} token={{ token }} url={{ vault_url }} proxies={{ proxies }}', errors='ignore').data.ssh_user }}"
          - my_ssh_passphrase: "{{ lookup('hashi_vault2', 'secret={{ vault_secret_path }} token={{ token }} url={{ vault_url }} proxies={{ proxies }}', errors='ignore').data['ssh_passphrase'] | b64decode }}"
          - my_ssh_private_key_data: "{{ lookup('hashi_vault2', 'secret={{ vault_secret_path }} token={{ token }} url={{ vault_url }} proxies={{ proxies }}', errors='ignore').data['ssh_private_key'] | b64decode }}"
    - set_fact:
        my_ssh_user: "{{ lookup('hashi_vault2', 'secret={{ vault_secret_path }} token={{ token }} url={{ vault_url }} proxies={{ proxies }}', errors='ignore').data.ssh_user }}"
        my_ssh_passphrase: "{{ lookup('hashi_vault2', 'secret={{ vault_secret_path }} token={{ token }} url={{ vault_url }} proxies={{ proxies }}', errors='ignore').data['ssh_passphrase'] | b64decode }}"
        my_ssh_private_key_data: "{{ lookup('hashi_vault2', 'secret={{ vault_secret_path }} token={{ token }} url={{ vault_url }} proxies={{ proxies }}', errors='ignore').data['ssh_private_key'] | b64decode }}"
    - debug:
        msg:
          - "my_ssh_user: {{ my_ssh_user }}"
          - "my_ssh_passphrase: {{ my_ssh_passphrase }}"
          - "my_ssh_private_key_data: {{ my_ssh_private_key_data }}"
    - copy: content="{{ my_ssh_private_key_data }}" dest=/tmp/my_ssh_private_key_file
    - name: Change file ownership, group and permissions
      file:
        path: /tmp/my_ssh_private_key_file
        mode: '0600'

