---
- name: Role ensures that the socks tunnel is setup
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ansible-role-socks5-tunnel

- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    token: myroot
    #vault_secret_path: /testkv/data/testsecrets/jumphost/
    vault_secret_path: /testkv/data/testsecrets/aakrhel001/
    #vault_url: http://ec2-52-201-237-93.compute-1.amazonaws.com:1234
    #proxies: '{}'
    #vault_url: http://172.17.0.3:1234
    #proxies: '{"http":"socks5h://localhost:1234","https":"socks5h://localhost:1234"}'
    #proxies: '{"http":"socks5h://unixsocket/tmp/mysock.sock","https":"socks5h://unixsocket/tmp/mysock.sock"}'
    vault_url: http://aakrhel001.yellowykt.com:1234
    proxies: {"http":"{{ jh1_socks_port if jh1_socks_port is defined else jh_socks_port }}","https:":"{{ jh1_socks_port if jh1_socks_port is defined else jh_socks_port }}"}
  tasks:
    - name: Start ssh-agent and Retrieve the SSH_AUTH_SOCK and SSH_AGENT_PID environment variables
      shell: |
        eval $(ssh-agent -s) > /dev/null
        echo '{"SSH_AUTH_SOCK":"'$SSH_AUTH_SOCK'","SSH_AGENT_PID":"'$SSH_AGENT_PID'"}'
      register: env_vars_stdout
    - set_fact:
        env_vars: "{{ env_vars_stdout.stdout }}"
    - name: Print the environment variables
      debug:
        msg: "{{ env_vars }}"
    - name: Check the ssh-agent
      shell: |
        ps -ef | grep ssh-agent
        true
    - debug:
        msg:
          - "vault_url: {{ vault_url }}"
          - "proxies: {{ proxies | to_json | replace(' ','') | string }}"
          - "vault_secret_path: {{ vault_secret_path }}"
    - set_fact:
        proxies_str: "{{ proxies | to_json | replace(' ','') | string }}"
    - debug:
        msg:
          - my_ssh_user: "{{ lookup('hashi_vault2', 'secret='+vault_secret_path+' token='+token+' url='+vault_url+' proxies='+proxies_str, errors='ignore').data.ssh_user }}"
          - my_ssh_passphrase: "{{ lookup('hashi_vault2', 'secret='+vault_secret_path+' token='+token+' url='+vault_url+' proxies='+proxies_str, errors='ignore').data.ssh_passphrase | b64decode }}"
          - my_ssh_private_key_data: "{{ lookup('hashi_vault2', 'secret='+vault_secret_path+' token='+token+' url='+vault_url+' proxies='+proxies_str, errors='ignore').data.ssh_private_key | b64decode }}"
    - set_fact:
        my_ssh_user: "{{ lookup('hashi_vault2', 'secret={{ vault_secret_path }} token={{ token }} url={{ vault_url }} proxies={{ proxies_str }}', errors='ignore').data.ssh_user }}"
        my_ssh_passphrase: "{{ lookup('hashi_vault2', 'secret={{ vault_secret_path }} token={{ token }} url={{ vault_url }} proxies={{ proxies_str }}', errors='ignore').data['ssh_passphrase'] | b64decode }}"
        my_ssh_private_key_data: "{{ lookup('hashi_vault2', 'secret={{ vault_secret_path }} token={{ token }} url={{ vault_url }} proxies={{ proxies_str }}', errors='ignore').data['ssh_private_key'] | b64decode }}"
    - debug:
        msg:
          - "my_ssh_user: {{ my_ssh_user }}"
          - "my_ssh_passphrase: {{ my_ssh_passphrase }}"
          - "my_ssh_private_key_data: {{ my_ssh_private_key_data }}"
    - copy: content="{{ my_ssh_private_key_data }}" dest=/tmp/my_ssh_private_key_file
    - name: Change file ownership, group and permissions
      file:
        path: /tmp/my_ssh_private_key_file
        mode: '0600'
    - set_fact:
        endpoint_ssh_private_key: "/tmp/my_ssh_private_key_file"
        endpoint_ssh_private_key_passphrase: "{{ my_ssh_passphrase }}"
        endpoint_ssh_user: "{{ my_ssh_user }}"
        endpoint_ssh_port: "{{ ansible_port if ansible_port is defined else 22 }}"
    - name: Show the SSH_AUTH_SOCK and SSH_AGENT_PID environment variables
      shell: |
        ps -ef | grep ssh-agent
        echo '{"SSH_AUTH_SOCK":"'$SSH_AUTH_SOCK'","SSH_AGENT_PID":"'$SSH_AGENT_PID'"}'

- name: add ssh key
  hosts: localhost
  connection: local
  gather_facts: false
  environment: "{{ env_vars }}"
  roles:
    - ansible-role-ssh-add-jumphosts-all
  tasks:
    - name: Show the SSH_AUTH_SOCK and SSH_AGENT_PID environment variables
      shell: |
        ps -ef | grep ssh-agent
        echo '{"SSH_AUTH_SOCK":"'$SSH_AUTH_SOCK'","SSH_AGENT_PID":"'$SSH_AGENT_PID'"}'

- hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: "{{ hostvars['127.0.0.1']['ansible_ssh_common_args'] }}"
    endpoint_ssh_private_key: "{{ hostvars['127.0.0.1']['endpoint_ssh_private_key'] }}"
    endpoint_ssh_user: "{{ hostvars['127.0.0.1']['endpoint_ssh_user'] }}"
    endpoint_ssh_port: "{{ hostvars['127.0.0.1']['endpoint_ssh_port'] }}"
  tasks:
    - include_vars:
        file: include_endpointcred.yaml
      when:
        - endpoint_ssh_private_key is defined and endpoint_ssh_private_key!=''
        - endpoint_ssh_user is defined and endpoint_ssh_user!=''
        - endpoint_ssh_port is defined and endpoint_ssh_port!=''
    - shell: echo Hello `hostname`
      register: result
    - debug:
        msg: "{{ result }}"
