---
jh_ssh_private_key: "{{ lookup('env','JH_SSH_PRIVATE_KEY') }}"
jh_ssh_private_key_passphrase: "{{ lookup('env', 'JH_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
jh1_ssh_private_key: "{{ lookup('env','JH1_SSH_PRIVATE_KEY') }}"
jh1_ssh_private_key_passphrase: "{{ lookup('env', 'JH1_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
jh2_ssh_private_key: "{{ lookup('env','JH2_SSH_PRIVATE_KEY') }}"
jh2_ssh_private_key_passphrase: "{{ lookup('env', 'JH2_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
jh3_ssh_private_key: "{{ lookup('env','JH3_SSH_PRIVATE_KEY') }}"
jh3_ssh_private_key_passphrase: "{{ lookup('env', 'JH3_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
jh4_ssh_private_key: "{{ lookup('env','JH4_SSH_PRIVATE_KEY') }}"
jh4_ssh_private_key_passphrase: "{{ lookup('env', 'JH4_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
jh5_ssh_private_key: "{{ lookup('env','JH5_SSH_PRIVATE_KEY') }}"
jh5_ssh_private_key_passphrase: "{{ lookup('env', 'JH5_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
jh6_ssh_private_key: "{{ lookup('env','JH6_SSH_PRIVATE_KEY') }}"
jh6_ssh_private_key_passphrase: "{{ lookup('env', 'JH6_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
bjh_ssh_private_key: "{{ lookup('env','BJH_SSH_PRIVATE_KEY') }}"
bjh_ssh_private_key_passphrase: "{{ lookup('env', 'BJH_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
bjh1_ssh_private_key: "{{ lookup('env','BJH1_SSH_PRIVATE_KEY') }}"
bjh1_ssh_private_key_passphrase: "{{ lookup('env', 'BJH1_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
bjh2_ssh_private_key: "{{ lookup('env','BJH2_SSH_PRIVATE_KEY') }}"
bjh2_ssh_private_key_passphrase: "{{ lookup('env', 'BJH2_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
bjh3_ssh_private_key: "{{ lookup('env','BJH3_SSH_PRIVATE_KEY') }}"
bjh3_ssh_private_key_passphrase: "{{ lookup('env', 'BJH3_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
bjh4_ssh_private_key: "{{ lookup('env','BJH4_SSH_PRIVATE_KEY') }}"
bjh4_ssh_private_key_passphrase: "{{ lookup('env', 'BJH4_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
bjh5_ssh_private_key: "{{ lookup('env','BJH5_SSH_PRIVATE_KEY') }}"
bjh5_ssh_private_key_passphrase: "{{ lookup('env', 'BJH5_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
bjh6_ssh_private_key: "{{ lookup('env','BJH6_SSH_PRIVATE_KEY') }}"
bjh6_ssh_private_key_passphrase: "{{ lookup('env', 'BJH6_SSH_PRIVATE_KEY_PASSPHRASE') or '' }}"
